### ISSUE TITLE
Inference time comparison

### ISSUE THREAD

**Issue by chrschinab** [spellml/examples#38]
Thank you very much for the nice and appealing article "Optimizing PyTorch models for fast CPU inference using Apache TVM". The comparison of the inference times in the end is very interesting. Here, two additional questions came to my mind:
1.) I just wonder what the inference time for the non-quantized (FP32) model after auto-tuning in TVM would be. Is this inference time larger or smaller than the inference time for the model quantized in pytorch and auto-tuned in TVM?
2.) What is the inference time for the quantized model after compilation in TVM without auto-tuning?

I am currently doing some experiments with a resnet18 model, where I find that that the inference time for the quantized model after auto-tuning is larger than without auto-tuning and, additionally, it is larger than the inference time of the non-quantized (FP32) model with auto-tuning.
I wonder if you see a similar behaviour or if it is different.

**Comment by ResidentMario** [comment]
My impression is that TVM is a very very very (very very very) ((very!)) complicated piece of cutting-edge technology. Either you're doing something wrong, or it's doing something. Hard to tell without being a TVM core dev, unfortunately.
